### PR TITLE
chore: rename master to main

### PR DESCRIPTION
**Pull request by Judge40**
TIS21-2345

### CODE REVIEW

**Comment by JosephKelly** [comment]
Is this project one which can be archived?  Not against updating it anyway just wanted to check if that's true & if it still makes sense in that context.

**Comment by Judge40** [comment]
> Is this project one which can be archived? Not against updating it anyway just wanted to check if that's true & if it still makes sense in that context.

I'm not sure exactly whats in this service anymore but its still a live part of reval.

**Review by JosephKelly — APPROVED** [review]
PLEASE DO NOT MERGE YET!

**Review by jayanta2018 — APPROVED** [review]

**Comment by DorisWongNHS** [comment]
@JosephKelly @Judge40 This project is still being used. The newly added notes endpoints are placed here and the "environment" endpoint is also here. We will have a discussion tomorrow to decide if we would refactor to split the non-recommendation stuffs to the core service.

**Pull request merged**
